const express= require("express")
const auth = require("../controller/auth")
const banquet = require("../controller/banquet/banquet")
const book = require("../controller/book/book")
const cart = require("../controller/cart/cart")
const dish = require("../controller/dish/dish")
const forgot_password = require("../controller/forgot-password")
const login = require("../controller/login")
const menu = require("../controller/menu/menu")
const order = require("../controller/order/order")
const recover_password = require("../controller/recover_password")
const reset_password = require("../controller/reset-password")
const signup = require("../controller/signup")
const staff = require("../controller/staff/staff")
const user = require("../controller/user")
const user2 = require("../controller/user/user")
const verify_mail = require("../controller/verify_email")
const uploadImage = require("../controller/uploadImage")
const blog = require("../controller/add_blog")
const confirm_payment = require("../controller/confirm_payment")
const bill = require("../controller/bill/bill")
const request_booking = require("../controller/request_booking")
const get_list_request_booking = require("../controller/get_list_request_booking")
const get_category = require("../controller/get_category")
const new_customer = require("../controller/new/new_customer")
const new_transaction = require("../controller/new/new_transaction")
const add_staff = require("../controller/add_staff")
const update_order_request = require("../controller/update_order_request")
const update_staff = require("../controller/update_staff")
const delete_contact = require("../controller/delete-contact")
const custom_book_dish = require("../controller/custom_book_dish")
const stats = require("../controller/stats/stats")
const delete_order_request = require("../controller/delete_order_request")
const get_list_blog = require("../controller/get_list_blog")
const get_detail_news = require("../controller/get_detail_news")
const router= express.Router()


router.post("/login", login)
router.post("/signup", signup)
router.post("/verify", verify_mail)
router.get("/", auth)
router.post("/forgot-password", forgot_password)
router.post("/recover-password", recover_password)
router.post("/reset-password", reset_password)
router.post("/api/user/update", user.update)
router.get("/order", order.get)
router.get("/menu/dish", menu.get)
router.get("/api/v1/dish", dish.getDetail)
router.get("/api/v1/banquet-hall/get", banquet.get)
router.post("/api/v3/banquet-hall/add", banquet.add)
router.get("/api/v1/banquet-hall/get/detail", banquet.getDetail)
router.get("/api/v2/staff/get/detail", staff.getDetail)
router.post("/api/v2/staff/get/update", staff.update)
router.get("/api/v3/user/get", user2.getAll)
router.post("/api/v3/user/update", user2.update)
router.post("/api/v3/user/delete", user2.delete)
router.post("/api/v3/banquet-hall/update", banquet.update)
router.post("/api/v1/book/banquet-hall", book.bookBanquetHall)
router.get("/api/v1/user/cart", cart.get)
router.post("/api/v1/book/dish", book.bookDish)
router.post("/api/v1/book/menu", book.bookMenu)
router.post("/api/order-request/add", order.newOrderRequest)
router.get("/api/order-request/get", order.getOrderRequest)
router.get("/api/v3/menu", menu.getMenu)
router.post("/api/v3/menu/update", menu.update)
router.post("/api/v3/menu/delete", menu.delete)
router.post("/api/v1/upload-image", uploadImage)
router.get("/api/v3/dish/get", dish.get)
router.post("/api/v3/menu/add", menu.add)
router.post("/api/v3/dish/add", dish.add)
router.post("/api/v3/dish/delete", dish.delete)
router.get("/api/v3/staff/get", staff.get)
router.post("/api/v3/blogs/add", blog.add)
router.post("/api/v2/paid/confirm", confirm_payment)
router.get("/api/v1/bill/get", bill.getBill)
router.post("/api/v1/request/booking", request_booking)
router.get("/api/v1/request/booking/get", get_list_request_booking)
router.get("/api/v1/category", get_category)
router.get("/api/v3/new/customer", new_customer)
router.get("/api/v3/new/transaction", new_transaction)
router.post("/api/v3/add_staff", add_staff)
router.post("/api/v2/update/order-request", update_order_request)
router.post("/api/v3/staff/update", update_staff)
router.delete("/api/v3/contact", delete_contact)
router.post("/api/v2/book/dish/custom", custom_book_dish)
router.get("/api/v3/stats/day", stats.statsDate)
router.get("/api/v3/stats/month", stats.statsMonth)
router.get("/api/v3/stats/year", stats.statsYear)
router.get("/api/v3/stats/range", stats.statsRange)
router.delete("/api/v2/order-request", delete_order_request)
router.post("/api/v3/dish/update", dish.update)
router.get("/api/v1/blogs", get_list_blog)
router.get("/api/v1/blogs/detail", get_detail_news )
router.post("/api/v3/banquet-hall/delete", banquet.delete)
router.post("/api/v3/blog/edit", blog.update)
router.post("/api/v3/blog/delete", blog.delete)

module.exports= router